export const ICON_NAMES = {
    ADD: "AddIcon",
    BACK: "BackIcon",
    CAR: "CarIcon",
    CHAT: "ChatIcon",
    EDIT: "EditIcon",
    HOME: "HomeIcon",
    LIST: "ListIcon",
    LOCATION: "LocationIcon",
    MAIL: "MailIcon",
    MOTORCYCLE: "MotorcycleIcon",
    PHONE: "PhoneIcon",
    SEARCH: "SearchIcon",
    SHARE: "ShareIcon",
    SHOP: "ShopIcon",
    TIME: "TimeIcon",
    TRUCK: "TruckIcon",
    USER: "UserIcon",
    VAN: "VanIcon",
}